-- Create "profiles" table
CREATE TABLE "public"."profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" uuid NOT NULL,
  "avatar" character varying NULL,
  "bio" character varying NULL,
  "location" character varying NULL,
  "nickname" character varying NOT NULL,
  "email" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_archived" boolean NULL,
  "archived_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "profile_user_id" to table: "profiles"
CREATE UNIQUE INDEX "profile_user_id" ON "public"."profiles" ("user_id");
-- Create index "profiles_nickname_key" to table: "profiles"
CREATE UNIQUE INDEX "profiles_nickname_key" ON "public"."profiles" ("nickname");
-- Create index "profiles_user_id_key" to table: "profiles"
CREATE UNIQUE INDEX "profiles_user_id_key" ON "public"."profiles" ("user_id");
